language: python
python:
 - "2.7"
 - "2.6"
install:
 - pip install -r requirements.txt coverage coveralls
 - python download_corpora.py
script:
  - coverage run --source newspaper tests/unit_tests.py
after_success:
  coveralls
